version: '3.6'

services:
  ###############
  ## AUXILLARY ##
  ###############

  # Nothing yet



  ###########
  ## BRANE ##
  ###########

  # "Proxy" service that can be targeted by local connections to be proxied (and encrypted with client auth) to remote hosts.
  brane-prx:
    image: brane-prx:${BRANE_VERSION:-latest}
    container_name: ${PRX_NAME:-brane-prx}
    command: --debug
    restart: always
    ports:
    - "0.0.0.0:50054:50054"
    - "0.0.0.0:50055:50055"
    volumes:
    - ${NODE_CONFIG_PATH}:/node.yml
    - ${PROXY:-}:${PROXY:-}
    - ${CERTS}:${CERTS}
    extra_hosts:
    - host.docker.internal:host-gateway

  # The service in charge of policy
  brane-chk:
    image: brane-chk:${BRANE_VERSION:-latest}
    init: true
    container_name: ${CHK_NAME:-brane-chk}
    command: -s "node-file-path=/node.yml"
    #ports:
    #- "0.0.0.0:${CHK_PORT}:${CHK_PORT}"
    restart: always
    environment:
    - ADDRESS=0.0.0.0:${CHK_PORT}
    volumes:
    - ${NODE_CONFIG_PATH}:/node.yml
    - ${POLICY_DB}:/data/policy.db
    - ${POLICY_DELIBERATION_SECRET}:/examples/config/jwk_set_delib.json
    - ${POLICY_EXPERT_SECRET}:/examples/config/jwk_set_expert.json
    extra_hosts:
    - host.docker.internal:host-gateway

  # The service in charge of the local container- and data registry
  brane-reg:
    image: brane-reg:${BRANE_VERSION:-latest}
    container_name: ${REG_NAME:-brane-reg}
    command: --debug
    #ports:
    #- "0.0.0.0:${REG_PORT}:${REG_PORT}"
    restart: always
    volumes:
    - ${NODE_CONFIG_PATH}:/node.yml
    - ${BACKEND}:${BACKEND}
    - ${CERTS}:${CERTS}
    - ${POLICY_DELIBERATION_SECRET}:${POLICY_DELIBERATION_SECRET}
    - ${DATA}:${DATA}
    - ${RESULTS}:${RESULTS}
    extra_hosts:
    - host.docker.internal:host-gateway

  # The service that is the 'main' service on the worker.
  brane-job:
    image: brane-job:${BRANE_VERSION:-latest}
    container_name: ${JOB_NAME:-brane-job}
    command: --debug
    #ports:
    #- "0.0.0.0:${JOB_PORT}:${JOB_PORT}"
    restart: always
    volumes:
    - ${NODE_CONFIG_PATH}:/node.yml
    - ${BACKEND}:${BACKEND}
    - ${CERTS}:${CERTS}
    - ${POLICY_DELIBERATION_SECRET}:${POLICY_DELIBERATION_SECRET}
    - ${PACKAGES}:${PACKAGES}
    - ${DATA}:${DATA}
    - ${RESULTS}:${RESULTS}
    - ${TEMP_DATA}:${TEMP_DATA}
    - ${TEMP_RESULTS}:${TEMP_RESULTS}
    - /var/run/docker.sock:/var/run/docker.sock
    extra_hosts:
    - host.docker.internal:host-gateway

networks:
  default:
    name: brane-worker-${LOCATION_ID}
