version: '3.6'

services:
  # "Proxy" service that can be targeted by local connections to be proxied (and encrypted with client auth) to remote hosts.
  brane-prx:
    image: brane-prx:${BRANE_VERSION:-latest}
    container_name: ${PRX_NAME:-brane-prx}
    restart: always
    ports:
    - "0.0.0.0:50051:50051"
    - "0.0.0.0:50052:50052"
    - "0.0.0.0:50053:50053"
    volumes:
    - ${NODE_CONFIG_PATH}:/node.yml
    - ${PROXY}:${PROXY}
    - ${CERTS}:${CERTS}
    extra_hosts:
    - host.docker.internal:host-gateway

networks:
  default:
    name: brane-proxy
