version: '3.6'

services:
  ###############
  ## AUXILLARY ##
  ###############

  # Database that contains package metadata
  aux-scylla:
    image: aux-scylla:${BRANE_VERSION:-latest}
    # ports:
    #   - "127.0.0.1:9042:9042"
    command: --smp 1
    restart: always
    labels:
    - kompose.service.type=nodeport
    - kompose.service.nodeport.port=9042



  ###########
  ## BRANE ##
  ###########

  # "Proxy" service that can be targeted by local connections to be proxied (and encrypted with client auth) to remote hosts.
  brane-prx:
    image: brane-prx:${BRANE_VERSION:-latest}
    container_name: ${PRX_NAME:-brane-prx}
    command: --debug
    restart: always
    ports:
    - "0.0.0.0:50054:50054"
    volumes:
    - ${NODE_CONFIG_PATH}:/node.yml
    - ${PROXY:-}:${PROXY:-}
    - ${CERTS}:${CERTS}
    extra_hosts:
    - host.docker.internal:host-gateway

  # The service in charge of package registry, downloading, uploading, etc
  brane-api:
    image: brane-api:${BRANE_VERSION:-latest}
    container_name: ${API_NAME:-brane-api}
    command: --debug
    restart: always
    ports:
    #- "0.0.0.0:${API_PORT}:${API_PORT}"
    - "0.0.0.0:50055:50055"
    volumes:
    - ${NODE_CONFIG_PATH}:/node.yml
    - ${INFRA}:${INFRA}
    - ${CERTS}:${CERTS}
    - ${PACKAGES}:${PACKAGES}
    depends_on:
    - aux-scylla
    - brane-prx
    # - aux-registry
    labels:
    - kompose.service.type=nodeport
    - kompose.service.nodeport.port=50055
    extra_hosts:
    - host.docker.internal:host-gateway

  # The service that accepts client connections and executes workflow control flow
  brane-drv:
    image: brane-drv:${BRANE_VERSION:-latest}
    container_name: ${DRV_NAME:-brane-drv}
    command: --debug
    restart: always
    ports:
    #- "0.0.0.0:${DRV_PORT}:${DRV_PORT}"
    - "0.0.0.0:50056:50056"
    volumes:
    - ${NODE_CONFIG_PATH}:/node.yml
    - ${INFRA}:${INFRA}
    depends_on:
    - brane-prx
    - brane-api
    labels:
    - kompose.service.type=nodeport
    - kompose.service.nodeport.port=50053
    extra_hosts:
    - host.docker.internal:host-gateway

  # # The service logging everything
  # brane-log:
  #   image: brane-log:${BRANE_VERSION:-latest}
  #   container_name: brane-log
  #   ports:
  #   - "127.0.0.1:50055:50055"
  #   restart: always
  #   environment:
  #     BROKERS: "aux-kafka:9092"
  #     EVENT_TOPIC: job-evt
  #     SCYLLA: "aux-scylla:9042"
  #   depends_on:
  #   - aux-kafka
  #   labels:
  #   - kompose.service.type=nodeport
  #   - kompose.service.nodeport.port=50055

  # The service that chooses the appropriate domain to run a job on
  brane-plr:
    image: brane-plr:${BRANE_VERSION:-latest}
    container_name: ${PLR_NAME:-brane-plr}
    restart: always
    volumes:
    - ${NODE_CONFIG_PATH}:/node.yml
    - ${INFRA}:${INFRA}
    extra_hosts:
    - host.docker.internal:host-gateway

networks:
  default:
    name: brane-central
