from collections import namedtuple
from unittest import mock

import matplotlib.pyplot as plt
import pandas as pd

# save the unpatched versions of the mocked functions
builtin_open = open
pandas_to_csv = pd.DataFrame.to_csv


def mock_open(*args, **kwargs):
    try:
        mock_dataset = next(d for d in MOCK_DATASETS if d.path == args[0])
        return mock.mock_open(read_data=mock_dataset.content)(*args, **kwargs)
    except StopIteration:
        # we keep DFS files in the test folder to avoid root permission errors
        _args = [*args]
        _args[0] = str(args[0]).replace("/data/", "")
        return builtin_open(*_args, **kwargs)


def mock_to_csv(df, path: str):
    pandas_to_csv(df, path.replace("/data/", ""))


def mock_savefig(path: str):
    plt.savefig(path.replace("/data/", ""))


MockDataset = namedtuple("MockDataset", ["path", "content"])

MOCK_DATASETS = [
    MockDataset(
        path="/data/dataset_test.csv",
        content='''id,keyword,location,text,text_stemmed,text_lemmatized,tokens
46,ablaze,London,birmingham wholesale market is ablaze bbc news - fire breaks out at birmingham's wholesale market  ,birmingham wholesale market is ablaze bbc news - fire breaks out at birmingham's wholesale market  ,birmingham wholesale market is ablaze bbc news - fire breaks out at birmingham's wholesale market  ,"['birmingham', 'wholesale', 'market', 'ablaze', 'bbc', 'news', 'fire', 'breaks', 'birmingham', 'wholesale', 'market']"
47,ablaze,Niall's place | SAF 12 SQUAD |, will you wear shorts for race ablaze ?, will you wear shorts for race ablaze ?, will you wear shorts for race ablaze ?,"['wear', 'shorts', 'race', 'ablaze']"
51,ablaze,NIGERIA,previouslyondoyintv: toke makinwaûªs marriage crisis sets nigerian twitter ablaze...  ,previouslyondoyintv: toke makinwaûªs marriage crisis sets nigerian twitter ablaze...  ,previouslyondoyintv: toke makinwaûªs marriage crisis sets nigerian twitter ablaze...  ,"['previouslyondoyintv', 'toke', 'makinwa', 'ûªs', 'marriage', 'crisis', 'sets', 'nigerian', 'twitter', 'ablaze']"
58,ablaze,Live On Webcam,check these out:         nsfw,check these out:         nsfw,check these out:         nsfw,"['check', 'nsfw']"
60,ablaze,"Los Angeles, Califnordia",psa: iûªm splitting my personalities.?? techies follow ?? burners follow ,psa: iûªm splitting my personalities.?? techies follow ?? burners follow ,psa: iûªm splitting my personalities.?? techies follow ?? burners follow ,"['psa', 'ûªm', 'splitting', 'personalities', 'techies', 'follow', 'burners', 'follow']"
69,ablaze,threeonefive. ,beware world ablaze sierra leone &amp; guap.,beware world ablaze sierra leone &amp; guap.,beware world ablaze sierra leone &amp; guap.,"['beware', 'world', 'ablaze', 'sierra', 'leone', 'amp', 'guap']"
70,ablaze,Washington State,burning man ablaze! by turban diva   via ,burning man ablaze! by turban diva   via ,burning man ablaze! by turban diva   via ,"['burning', 'man', 'ablaze', 'turban', 'diva', 'via']"
72,ablaze,"Whoop Ass, Georgia",not a diss song. people will take 1 thing and run with it. smh it's an eye opener though. he is about 2 set the game ablaze ,not a diss song. people will take 1 thing and run with it. smh it's an eye opener though. he is about 2 set the game ablaze ,not a diss song. people will take 1 thing and run with it. smh it's an eye opener though. he is about 2 set the game ablaze ,"['diss', 'song', 'people', 'take', '1', 'thing', 'run', 'smh', 'eye', 'opener', 'though', '2', 'set', 'game', 'ablaze']"
75,ablaze,India,rape victim dies as she sets herself ablaze: a 16-year-old girl died of burn injuries as she set herself ablazeû_  ,rape victim dies as she sets herself ablaze: a 16-year-old girl died of burn injuries as she set herself ablazeû_  ,rape victim dies as she sets herself ablaze: a 16-year-old girl died of burn injuries as she set herself ablazeû_  ,"['rape', 'victim', 'dies', 'sets', 'ablaze', '16', 'year', 'old', 'girl', 'died', 'burn', 'injuries', 'set', 'ablaze', 'û_']"
84,ablaze,,setting myself ablaze  ,setting myself ablaze  ,setting myself ablaze  ,"['setting', 'ablaze']"
87,ablaze,"scarborough, ontario", the bins in front of the field by my house wer set ablaze the other day flames went rite up the hydro pole wonder if it was him, the bins in front of the field by my house wer set ablaze the other day flames went rite up the hydro pole wonder if it was him, the bins in front of the field by my house wer set ablaze the other day flames went rite up the hydro pole wonder if it was him,"['bins', 'front', 'field', 'house', 'wer', 'set', 'ablaze', 'day', 'flames', 'went', 'rite', 'hydro', 'pole', 'wonder']"
88,ablaze,,nowplaying alfons - ablaze 2015 on puls radio pulsradio  ,nowplaying alfons - ablaze 2015 on puls radio pulsradio  ,nowplaying alfons - ablaze 2015 on puls radio pulsradio  ,"['nowplaying', 'alfons', 'ablaze', '2015', 'puls', 'radio', 'pulsradio']"
90,ablaze,"121 N La Salle St, Suite 500",'burning rahm': let's hope city hall builds a giant wooden mayoral effigy 100 feet tall &amp; sets it ablaze.   ,'burning rahm': let's hope city hall builds a giant wooden mayoral effigy 100 feet tall &amp; sets it ablaze.   ,'burning rahm': let's hope city hall builds a giant wooden mayoral effigy 100 feet tall &amp; sets it ablaze.   ,"['burning', 'rahm', 'let', 'hope', 'city', 'hall', 'builds', 'giant', 'wooden', 'mayoral', 'effigy', '100', 'feet', 'tall', 'amp', 'sets', 'ablaze']"
94,ablaze,Wandering,  hurt but her eyes ablaze with insulted anger.,  hurt but her eyes ablaze with insulted anger.,  hurt but her eyes ablaze with insulted anger.,"['hurt', 'eyes', 'ablaze', 'insulted', 'anger']"
99,accident,"Homewood, PA",accident cleared in paturnpike on patp eb between pa-18 and cranberry slow back to traffic  ,accident cleared in paturnpike on patp eb between pa-18 and cranberry slow back to traffic  ,accident cleared in paturnpike on patp eb between pa-18 and cranberry slow back to traffic  ,"['accident', 'cleared', 'paturnpike', 'patp', 'eb', 'pa', '18', 'cranberry', 'slow', 'back', 'traffic']"
101,accident,,just got to love burning your self on a damn curling wand... i swear someone needs to take it away from me cuase i'm just accident prone.,just got to love burning your self on a damn curling wand... i swear someone needs to take it away from me cuase i'm just accident prone.,just got to love burning your self on a damn curling wand... i swear someone needs to take it away from me cuase i'm just accident prone.,"['got', 'love', 'burning', 'self', 'damn', 'curling', 'wand', 'swear', 'someone', 'needs', 'take', 'away', 'cuase', 'accident', 'prone']"
103,accident,,i hate badging shit in accident,i hate badging shit in accid,i hate badging shit in accid,"['hate', 'badging', 'shit', 'accid']"
106,accident,USA,3: car recorder zeroedgeå¨ dual-lens car camera vehicle traffic/driving history/accident camcorder  large re...  ,3: car recorder zeroedgeå¨ dual-lens car camera vehicle traffic/driving history/accident camcorder  large re...  ,3: car recorder zeroedgeå¨ dual-lens car camera vehicle traffic/driving history/accident camcorder  large re...  ,"['3', 'car', 'recorder', 'zeroedgeå', 'dual', 'lens', 'car', 'camera', 'vehicle', 'traffic', 'driving', 'history', 'accident', 'camcorder', 'large']"
108,accident,Massachusetts,coincidence or curse? still unresolved secrets from past   accident,coincidence or curse? still unresolved secrets from past   accid,coincidence or curse? still unresolved secrets from past   accid,"['coincidence', 'curse', 'still', 'unresolved', 'secrets', 'past', 'accid']"
111,accident,Bexhill,  accident on a27 near lewes is it kingston roundabout rather than a283,  accident on a27 near lewes is it kingston roundabout rather than a283,  accident on a27 near lewes is it kingston roundabout rather than a283,"['accident', 'a27', 'near', 'lewes', 'kingston', 'roundabout', 'rather', 'a283']"
115,accident,Anime World, if you pretend to feel a certain way the feeling can become genuine all by accident. -hei (darker than black) manga anime, if you pretend to feel a certain way the feeling can become genuine all by accident. -hei (darker than black) manga anim, if you pretend to feel a certain way the feeling can become genuine all by accident. -hei (darker than black) manga anim,"['pretend', 'feel', 'certain', 'way', 'feeling', 'become', 'genuine', 'accident', 'hei', 'darker', 'black', 'manga', 'anim']"
116,accident,,for legal and medical referral service  call us at: 1-800-465-87332 accident slipandfall dogbite,for legal and medical referral service  call us at: 1-800-465-87332 accident slipandfall dogbit,for legal and medical referral service  call us at: 1-800-465-87332 accident slipandfall dogbit,"['legal', 'medical', 'referral', 'service', 'call', 'us', '1', '800', '465', '87332', 'accident', 'slipandfall', 'dogbit']"
122,accident,"Cowtown, Caliii !!",there's a construction guy working on the disney store and he has huge gauges in his ears ?? ...that is a bloody accident waiting to happen,there's a construction guy working on the disney store and he has huge gauges in his ears ?? ...that is a bloody accident waiting to happen,there's a construction guy working on the disney store and he has huge gauges in his ears ?? ...that is a bloody accident waiting to happen,"['construction', 'guy', 'working', 'disney', 'store', 'huge', 'gauges', 'ears', 'bloody', 'accident', 'waiting', 'happen']"
123,accident,,  i feel like i'm going to do it on accident. teesha is gonna come out??,  i feel like i'm going to do it on accident. teesha is gonna come out??,  i feel like i'm going to do it on accident. teesha is gonna come out??,"['feel', 'like', 'going', 'accident', 'teesha', 'gonna', 'come']"
124,accident,"All Motorways, UK",on the m42 northbound between junctions j3 and j3a there are currently delays of 10 mins due to an accident c...  ,on the m42 northbound between junctions j3 and j3a there are currently delays of 10 mins due to an accident c...  ,on the m42 northbound between junctions j3 and j3a there are currently delays of 10 mins due to an accident c...  ,"['m42', 'northbound', 'junctions', 'j3', 'j3a', 'currently', 'delays', '10', 'mins', 'due', 'accident', 'c']"
125,accident,"Frankfurt, Germany",  so if i say that i met her by accident this week- would you be super jelly dave? :p,  so if i say that i met her by accident this week- would you be super jelly dave? :p,  so if i say that i met her by accident this week- would you be super jelly dave? :p,"['say', 'met', 'accident', 'week', 'would', 'super', 'jelly', 'dave', 'p']"
127,accident,"Gresham, OR",accident - hit and run - cold at 500 block of se vista ter gresham or [gresham police pg15000044357] 10:35 pdx911,accident - hit and run - cold at 500 block of se vista ter gresham or [gresham police pg15000044357] 10:35 pdx911,accident - hit and run - cold at 500 block of se vista ter gresham or [gresham police pg15000044357] 10:35 pdx911,"['accident', 'hit', 'run', 'cold', '500', 'block', 'se', 'vista', 'ter', 'gresham', 'gresham', 'police', 'pg15000044357', '10', '35', 'pdx911']"
'''),
    MockDataset(
        path="/data/dataset_submission.csv",
        content='''id,target
46,1
47,0
51,1
58,0
60,0
69,0
70,0
72,0
75,1
84,0
87,0
88,0
90,0
94,0
99,1
101,0
103,0
106,1
108,0
111,0
115,0
116,0
122,0
123,0
124,1
125,0
127,0
'''),
    MockDataset(
        path="/data/dataset_train.csv",
        content='''id,keyword,location,text,target,text_stemmed,text_lemmatized,tokens,bigrams
50,ablaze,AFRICA,africanbaze: breaking news:nigeria flag set ablaze in aba.  ,1,africanbaze: breaking news:nigeria flag set ablaze in aba.  ,africanbaze: breaking news:nigeria flag set ablaze in aba.  ,"['africanbaze', 'breaking', 'news', 'nigeria', 'flag', 'set', 'ablaze', 'aba']","['africanbaze_breaking', 'breaking_news', 'news_nigeria', 'nigeria_flag', 'flag_set', 'set_ablaze', 'ablaze_aba']"
52,ablaze,"Philadelphia, PA",crying out for more! set me ablaze,0,crying out for more! set me ablaz,crying out for more! set me ablaz,"['crying', 'set', 'ablaz']","['crying_set', 'set_ablaz']"
53,ablaze,"London, UK",on plus side look at the sky last night it was ablaze  ,0,on plus side look at the sky last night it was ablaze  ,on plus side look at the sky last night it was ablaze  ,"['plus', 'side', 'look', 'sky', 'last', 'night', 'ablaze']","['plus_side', 'side_look', 'look_sky', 'sky_last', 'last_night', 'night_ablaze']"
54,ablaze,Pretoria, mufc they've built so much hype around new acquisitions but i doubt they will set the epl ablaze this season.,0, mufc they've built so much hype around new acquisitions but i doubt they will set the epl ablaze this season., mufc they've built so much hype around new acquisitions but i doubt they will set the epl ablaze this season.,"['mufc', 'built', 'much', 'hype', 'around', 'new', 'acquisitions', 'doubt', 'set', 'epl', 'ablaze', 'season']","['mufc_built', 'built_much', 'much_hype', 'hype_around', 'around_new', 'new_acquisitions', 'acquisitions_doubt', 'doubt_set', 'set_epl', 'epl_ablaze', 'ablaze_season']"
55,ablaze,World Wide!!,inec office in abia set ablaze -  ,1,inec office in abia set ablaze -  ,inec office in abia set ablaze -  ,"['inec', 'office', 'abia', 'set', 'ablaze']","['inec_office', 'office_abia', 'abia_set', 'set_ablaze']"
56,ablaze,,barbados bridgetown jamaica ûò two cars set ablaze: santa cruz ûó head of the st elizabeth police superintende...   ,1,barbados bridgetown jamaica ûò two cars set ablaze: santa cruz ûó head of the st elizabeth police superintende...   ,barbados bridgetown jamaica ûò two cars set ablaze: santa cruz ûó head of the st elizabeth police superintende...   ,"['barbados', 'bridgetown', 'jamaica', 'ûò', 'two', 'cars', 'set', 'ablaze', 'santa', 'cruz', 'ûó', 'head', 'st', 'elizabeth', 'police', 'superintende']","['barbados_bridgetown', 'bridgetown_jamaica', 'jamaica_ûò', 'ûò_two', 'two_cars', 'cars_set', 'set_ablaze', 'ablaze_santa', 'santa_cruz', 'cruz_ûó', 'ûó_head', 'head_st', 'st_elizabeth', 'elizabeth_police', 'police_superintende']"
57,ablaze,Paranaque City,ablaze for you lord :d,0,ablaze for you lord :d,ablaze for you lord :d,"['ablaze', 'lord']",['ablaze_lord']
59,ablaze,Live On Webcam,check these out:         nsfw,0,check these out:         nsfw,check these out:         nsfw,"['check', 'nsfw']",['check_nsfw']
61,ablaze,,on the outside you're ablaze and alivebut you're dead inside,0,on the outside you're ablaze and alivebut you're dead insid,on the outside you're ablaze and alivebut you're dead insid,"['outside', 'ablaze', 'alivebut', 'dead', 'insid']","['outside_ablaze', 'ablaze_alivebut', 'alivebut_dead', 'dead_insid']"
62,ablaze,milky way,had an awesome time visiting the cfc head office the ancop site and ablaze. thanks to tita vida for taking care of us ??,0,had an awesome time visiting the cfc head office the ancop site and ablaze. thanks to tita vida for taking care of us ??,had an awesome time visiting the cfc head office the ancop site and ablaze. thanks to tita vida for taking care of us ??,"['awesome', 'time', 'visiting', 'cfc', 'head', 'office', 'ancop', 'site', 'ablaze', 'thanks', 'tita', 'vida', 'taking', 'care', 'us']","['awesome_time', 'time_visiting', 'visiting_cfc', 'cfc_head', 'head_office', 'office_ancop', 'ancop_site', 'site_ablaze', 'ablaze_thanks', 'thanks_tita', 'tita_vida', 'vida_taking', 'taking_care', 'care_us']"
63,ablaze,,soooo pumped for ablaze ???? ,0,soooo pumped for ablaze ???? ,soooo pumped for ablaze ???? ,"['soooo', 'pumped', 'ablaze']","['soooo_pumped', 'pumped_ablaze']"
64,ablaze,,i wanted to set chicago ablaze with my preaching... but not my hotel!  ,0,i wanted to set chicago ablaze with my preaching... but not my hotel!  ,i wanted to set chicago ablaze with my preaching... but not my hotel!  ,"['wanted', 'set', 'chicago', 'ablaze', 'preaching', 'hotel']","['wanted_set', 'set_chicago', 'chicago_ablaze', 'ablaze_preaching', 'preaching_hotel']"
65,ablaze,,i gained 3 followers in the last week. you? know your stats and grow with  ,0,i gained 3 followers in the last week. you? know your stats and grow with  ,i gained 3 followers in the last week. you? know your stats and grow with  ,"['gained', '3', 'followers', 'last', 'week', 'know', 'stats', 'grow']","['gained_3', '3_followers', 'followers_last', 'last_week', 'week_know', 'know_stats', 'stats_grow']"
66,ablaze,"GREENSBORO,NORTH CAROLINA",how the west was burned: thousands of wildfires ablaze in california alone  ,1,how the west was burned: thousands of wildfires ablaze in california alone  ,how the west was burned: thousands of wildfires ablaze in california alone  ,"['west', 'burned', 'thousands', 'wildfires', 'ablaze', 'california', 'alone']","['west_burned', 'burned_thousands', 'thousands_wildfires', 'wildfires_ablaze', 'ablaze_california', 'california_alone']"
67,ablaze,,building the perfect tracklist to life leave the streets ablaze,0,building the perfect tracklist to life leave the streets ablaz,building the perfect tracklist to life leave the streets ablaz,"['building', 'perfect', 'tracklist', 'life', 'leave', 'streets', 'ablaz']","['building_perfect', 'perfect_tracklist', 'tracklist_life', 'life_leave', 'leave_streets', 'streets_ablaz']"
68,ablaze,Live On Webcam,check these out:         nsfw,0,check these out:         nsfw,check these out:         nsfw,"['check', 'nsfw']",['check_nsfw']
71,ablaze,England.,first night with retainers in. it's quite weird. better get used to it; i have to wear them every single night for the next year at least.,0,first night with retainers in. it's quite weird. better get used to it; i have to wear them every single night for the next year at least.,first night with retainers in. it's quite weird. better get used to it; i have to wear them every single night for the next year at least.,"['first', 'night', 'retainers', 'quite', 'weird', 'better', 'get', 'used', 'wear', 'every', 'single', 'night', 'next', 'year', 'least']","['first_night', 'night_retainers', 'retainers_quite', 'quite_weird', 'weird_better', 'better_get', 'get_used', 'used_wear', 'wear_every', 'every_single', 'single_night', 'night_next', 'next_year', 'year_least']"
73,ablaze,"Sheffield Township, Ohio",deputies: man shot before brighton home set ablaze  ,1,deputies: man shot before brighton home set ablaze  ,deputies: man shot before brighton home set ablaze  ,"['deputies', 'man', 'shot', 'brighton', 'home', 'set', 'ablaze']","['deputies_man', 'man_shot', 'shot_brighton', 'brighton_home', 'home_set', 'set_ablaze']"
74,ablaze,India,man wife get six years jail for setting ablaze niece ,1,man wife get six years jail for setting ablaze niece ,man wife get six years jail for setting ablaze niece ,"['man', 'wife', 'get', 'six', 'years', 'jail', 'setting', 'ablaze', 'niece']","['man_wife', 'wife_get', 'get_six', 'six_years', 'years_jail', 'jail_setting', 'setting_ablaze', 'ablaze_niece']"
76,ablaze,Barbados,santa cruz ûó head of the st elizabeth police superintendent lanford salmon has r ... -    ,0,santa cruz ûó head of the st elizabeth police superintendent lanford salmon has r ... -    ,santa cruz ûó head of the st elizabeth police superintendent lanford salmon has r ... -    ,"['santa', 'cruz', 'ûó', 'head', 'st', 'elizabeth', 'police', 'superintendent', 'lanford', 'salmon', 'r']","['santa_cruz', 'cruz_ûó', 'ûó_head', 'head_st', 'st_elizabeth', 'elizabeth_police', 'police_superintendent', 'superintendent_lanford', 'lanford_salmon', 'salmon_r']"
77,ablaze,Anaheim,police: arsonist deliberately set black church in north carolinaåêablaze  ,1,police: arsonist deliberately set black church in north carolinaåêablaze  ,police: arsonist deliberately set black church in north carolinaåêablaze  ,"['police', 'arsonist', 'deliberately', 'set', 'black', 'church', 'north', 'carolinaåêablaze']","['police_arsonist', 'arsonist_deliberately', 'deliberately_set', 'set_black', 'black_church', 'church_north', 'north_carolinaåêablaze']"
78,ablaze,Abuja,noches el-bestia ': happy to see my teammates and training hard ?? goodnight gunners.??????  ,0,noches el-bestia ': happy to see my teammates and training hard ?? goodnight gunners.??????  ,noches el-bestia ': happy to see my teammates and training hard ?? goodnight gunners.??????  ,"['noches', 'el', 'bestia', 'happy', 'see', 'teammates', 'training', 'hard', 'goodnight', 'gunners']","['noches_el', 'el_bestia', 'bestia_happy', 'happy_see', 'see_teammates', 'teammates_training', 'training_hard', 'hard_goodnight', 'goodnight_gunners']"
79,ablaze,USA,kurds trampling on turkmen flag later set it ablaze while others vandalized offices of turkmen front in diyala  ,1,kurds trampling on turkmen flag later set it ablaze while others vandalized offices of turkmen front in diyala  ,kurds trampling on turkmen flag later set it ablaze while others vandalized offices of turkmen front in diyala  ,"['kurds', 'trampling', 'turkmen', 'flag', 'later', 'set', 'ablaze', 'others', 'vandalized', 'offices', 'turkmen', 'front', 'diyala']","['kurds_trampling', 'trampling_turkmen', 'turkmen_flag', 'flag_later', 'later_set', 'set_ablaze', 'ablaze_others', 'others_vandalized', 'vandalized_offices', 'offices_turkmen', 'turkmen_front', 'front_diyala']"
80,ablaze,South Africa,truck ablaze : r21. voortrekker ave. outside or tambo intl. cargo section.  ,1,truck ablaze : r21. voortrekker ave. outside or tambo intl. cargo section.  ,truck ablaze : r21. voortrekker ave. outside or tambo intl. cargo section.  ,"['truck', 'ablaze', 'r21', 'voortrekker', 'ave', 'outside', 'tambo', 'intl', 'cargo', 'section']","['truck_ablaze', 'ablaze_r21', 'r21_voortrekker', 'voortrekker_ave', 'ave_outside', 'outside_tambo', 'tambo_intl', 'intl_cargo', 'cargo_section']"
81,ablaze,"Sao Paulo, Brazil",set our hearts ablaze and every city was a gift and every skyline was like a kiss upon the lips @û_  ,0,set our hearts ablaze and every city was a gift and every skyline was like a kiss upon the lips @û_  ,set our hearts ablaze and every city was a gift and every skyline was like a kiss upon the lips @û_  ,"['set', 'hearts', 'ablaze', 'every', 'city', 'gift', 'every', 'skyline', 'like', 'kiss', 'upon', 'lips', 'û_']","['set_hearts', 'hearts_ablaze', 'ablaze_every', 'every_city', 'city_gift', 'gift_every', 'every_skyline', 'skyline_like', 'like_kiss', 'kiss_upon', 'upon_lips', 'lips_û_']"
82,ablaze,hollywoodland ,they sky was ablaze tonight in los angeles. i'm expecting ig and fb to be filled with sunset shots if i know my peeps!!,0,they sky was ablaze tonight in los angeles. i'm expecting ig and fb to be filled with sunset shots if i know my peeps!!,they sky was ablaze tonight in los angeles. i'm expecting ig and fb to be filled with sunset shots if i know my peeps!!,"['sky', 'ablaze', 'tonight', 'los', 'angeles', 'expecting', 'ig', 'fb', 'filled', 'sunset', 'shots', 'know', 'peeps']","['sky_ablaze', 'ablaze_tonight', 'tonight_los', 'los_angeles', 'angeles_expecting', 'expecting_ig', 'ig_fb', 'fb_filled', 'filled_sunset', 'sunset_shots', 'shots_know', 'know_peeps']"
83,ablaze,"Edmonton, Alberta - Treaty 6",how the west was burned: thousands of wildfires ablaze in california alone   climate energy  ,1,how the west was burned: thousands of wildfires ablaze in california alone   climate energy  ,how the west was burned: thousands of wildfires ablaze in california alone   climate energy  ,"['west', 'burned', 'thousands', 'wildfires', 'ablaze', 'california', 'alone', 'climate', 'energy']","['west_burned', 'burned_thousands', 'thousands_wildfires', 'wildfires_ablaze', 'ablaze_california', 'california_alone', 'alone_climate', 'climate_energy']"
85,ablaze,,revel in yours wmv videos by means of mac farewell ablaze wmv en route to dvd: gtxrwm,0,revel in yours wmv videos by means of mac farewell ablaze wmv en route to dvd: gtxrwm,revel in yours wmv videos by means of mac farewell ablaze wmv en route to dvd: gtxrwm,"['revel', 'wmv', 'videos', 'means', 'mac', 'farewell', 'ablaze', 'wmv', 'en', 'route', 'dvd', 'gtxrwm']","['revel_wmv', 'wmv_videos', 'videos_means', 'means_mac', 'mac_farewell', 'farewell_ablaze', 'ablaze_wmv', 'wmv_en', 'en_route', 'route_dvd', 'dvd_gtxrwm']"
86,ablaze,Inang Pamantasan,progressive greetings!in about a month students would have set their pens ablaze in the torch publications'...  ,0,progressive greetings!in about a month students would have set their pens ablaze in the torch publications'...  ,progressive greetings!in about a month students would have set their pens ablaze in the torch publications'...  ,"['progressive', 'greetings', 'month', 'students', 'would', 'set', 'pens', 'ablaze', 'torch', 'publications']","['progressive_greetings', 'greetings_month', 'month_students', 'students_would', 'would_set', 'set_pens', 'pens_ablaze', 'ablaze_torch', 'torch_publications']"
89,ablaze,Twitter Lockout in progress,rene ablaze &amp; jacinta - secret 2k13 (fallen skies edit) - mar 30 2013   ,0,rene ablaze &amp; jacinta - secret 2k13 (fallen skies edit) - mar 30 2013   ,rene ablaze &amp; jacinta - secret 2k13 (fallen skies edit) - mar 30 2013   ,"['rene', 'ablaze', 'amp', 'jacinta', 'secret', '2k13', 'fallen', 'skies', 'edit', 'mar', '30', '2013']","['rene_ablaze', 'ablaze_amp', 'amp_jacinta', 'jacinta_secret', 'secret_2k13', '2k13_fallen', 'fallen_skies', 'skies_edit', 'edit_mar', 'mar_30', '30_2013']"
91,ablaze,"Concord, CA", steve these fires out here are something else! california is a tinderbox - and this clown was setting my 'hood ablaze ,1, steve these fires out here are something else! california is a tinderbox - and this clown was setting my 'hood ablaze , steve these fires out here are something else! california is a tinderbox - and this clown was setting my 'hood ablaze ,"['steve', 'fires', 'something', 'else', 'california', 'tinderbox', 'clown', 'setting', 'hood', 'ablaze']","['steve_fires', 'fires_something', 'something_else', 'else_california', 'california_tinderbox', 'tinderbox_clown', 'clown_setting', 'setting_hood', 'hood_ablaze']"
92,ablaze,"Calgary, AB",nowplaying: rene ablaze &amp; ian buff - magnitude    edm,0,nowplaying: rene ablaze &amp; ian buff - magnitude    edm,nowplaying: rene ablaze &amp; ian buff - magnitude    edm,"['nowplaying', 'rene', 'ablaze', 'amp', 'ian', 'buff', 'magnitude', 'edm']","['nowplaying_rene', 'rene_ablaze', 'ablaze_amp', 'amp_ian', 'ian_buff', 'buff_magnitude', 'magnitude_edm']"
93,ablaze,Birmingham, huge fire at wholesale markets ablaze  ,1, huge fire at wholesale markets ablaze  , huge fire at wholesale markets ablaze  ,"['huge', 'fire', 'wholesale', 'markets', 'ablaze']","['huge_fire', 'fire_wholesale', 'wholesale_markets', 'markets_ablaze']"
95,ablaze,San Francisco, what time does your talk go until? i don't know if i can make it due to work.,0, what time does your talk go until? i don't know if i can make it due to work., what time does your talk go until? i don't know if i can make it due to work.,"['time', 'talk', 'go', 'know', 'make', 'due', 'work']","['time_talk', 'talk_go', 'go_know', 'know_make', 'make_due', 'due_work']"
96,accident,CLVLND,'i can't have kids cuz i got in a bicycle accident &amp; split my testicles. it's impossible for me to have kids' michael you are the father,0,'i can't have kids cuz i got in a bicycle accident &amp; split my testicles. it's impossible for me to have kids' michael you are the fath,'i can't have kids cuz i got in a bicycle accident &amp; split my testicles. it's impossible for me to have kids' michael you are the fath,"['kids', 'cuz', 'got', 'bicycle', 'accident', 'amp', 'split', 'testicles', 'impossible', 'kids', 'michael', 'fath']","['kids_cuz', 'cuz_got', 'got_bicycle', 'bicycle_accident', 'accident_amp', 'amp_split', 'split_testicles', 'testicles_impossible', 'impossible_kids', 'kids_michael', 'michael_fath']"
97,accident,"Nashville, TN",accident on i-24 w nashvilletraffic. traffic moving 8m slower than usual.  ,1,accident on i-24 w nashvilletraffic. traffic moving 8m slower than usual.  ,accident on i-24 w nashvilletraffic. traffic moving 8m slower than usual.  ,"['accident', '24', 'w', 'nashvilletraffic', 'traffic', 'moving', '8m', 'slower', 'usual']","['accident_24', '24_w', 'w_nashvilletraffic', 'nashvilletraffic_traffic', 'traffic_moving', 'moving_8m', '8m_slower', 'slower_usual']"
98,accident,"Santa Clara, CA",accident center lane blocked in santaclara on us-101 nb before great america pkwy bayarea traffic  ,1,accident center lane blocked in santaclara on us-101 nb before great america pkwy bayarea traffic  ,accident center lane blocked in santaclara on us-101 nb before great america pkwy bayarea traffic  ,"['accident', 'center', 'lane', 'blocked', 'santaclara', 'us', '101', 'nb', 'great', 'america', 'pkwy', 'bayarea', 'traffic']","['accident_center', 'center_lane', 'lane_blocked', 'blocked_santaclara', 'santaclara_us', 'us_101', '101_nb', 'nb_great', 'great_america', 'america_pkwy', 'pkwy_bayarea', 'bayarea_traffic']"
100,accident,UK,  had a personalinjury accident this summer? read our advice &amp; see how a solicitor can help otleyhour,0,  had a personalinjury accident this summer? read our advice &amp; see how a solicitor can help otleyhour,  had a personalinjury accident this summer? read our advice &amp; see how a solicitor can help otleyhour,"['personalinjury', 'accident', 'summer', 'read', 'advice', 'amp', 'see', 'solicitor', 'help', 'otleyhour']","['personalinjury_accident', 'accident_summer', 'summer_read', 'read_advice', 'advice_amp', 'amp_see', 'see_solicitor', 'solicitor_help', 'help_otleyhour']"
102,accident,"St. Louis, MO",stlouis caraccidentlawyer speeding among top causes of teen accidents     car accident teeû_,0,stlouis caraccidentlawyer speeding among top causes of teen accidents     car accident teeû_,stlouis caraccidentlawyer speeding among top causes of teen accidents     car accident teeû_,"['stlouis', 'caraccidentlawyer', 'speeding', 'among', 'top', 'causes', 'teen', 'accidents', 'car', 'accident', 'tee', 'û_']","['stlouis_caraccidentlawyer', 'caraccidentlawyer_speeding', 'speeding_among', 'among_top', 'top_causes', 'causes_teen', 'teen_accidents', 'accidents_car', 'car_accident', 'accident_tee', 'tee_û_']"
104,accident,"Walker County, Alabama",reported motor vehicle accident in curry on herman rd near stephenson involving an overturned vehicle. please use...  ,1,reported motor vehicle accident in curry on herman rd near stephenson involving an overturned vehicle. please use...  ,reported motor vehicle accident in curry on herman rd near stephenson involving an overturned vehicle. please use...  ,"['reported', 'motor', 'vehicle', 'accident', 'curry', 'herman', 'rd', 'near', 'stephenson', 'involving', 'overturned', 'vehicle', 'please', 'use']","['reported_motor', 'motor_vehicle', 'vehicle_accident', 'accident_curry', 'curry_herman', 'herman_rd', 'rd_near', 'near_stephenson', 'stephenson_involving', 'involving_overturned', 'overturned_vehicle', 'vehicle_please', 'please_use']"
105,accident,Australia,bigrigradio live accident awareness,1,bigrigradio live accident awar,bigrigradio live accident awar,"['bigrigradio', 'live', 'accident', 'awar']","['bigrigradio_live', 'live_accident', 'accident_awar']"
107,accident,North Carolina,i-77 mile marker 31 south mooresville  iredell vehicle accident ramp closed at 8/6 1:18 pm,1,i-77 mile marker 31 south mooresville  iredell vehicle accident ramp closed at 8/6 1:18 pm,i-77 mile marker 31 south mooresville  iredell vehicle accident ramp closed at 8/6 1:18 pm,"['77', 'mile', 'marker', '31', 'south', 'mooresville', 'iredell', 'vehicle', 'accident', 'ramp', 'closed', '8', '6', '1', '18', 'pm']","['77_mile', 'mile_marker', 'marker_31', '31_south', 'south_mooresville', 'mooresville_iredell', 'iredell_vehicle', 'vehicle_accident', 'accident_ramp', 'ramp_closed', 'closed_8', '8_6', '6_1', '1_18', '18_pm']"
109,accident,,rt : sleeping pills double your risk of a car accident  ,0,rt : sleeping pills double your risk of a car accident  ,rt : sleeping pills double your risk of a car accident  ,"['rt', 'sleeping', 'pills', 'double', 'risk', 'car', 'accident']","['rt_sleeping', 'sleeping_pills', 'pills_double', 'double_risk', 'risk_car', 'car_accident']"
110,accident,Norf Carolina,'by accident' they knew what was gon happen  ,0,'by accident' they knew what was gon happen  ,'by accident' they knew what was gon happen  ,"['accident', 'knew', 'gon', 'happen']","['accident_knew', 'knew_gon', 'gon_happen']"
112,accident,"San Mateo County, CA",traffic accident n cabrillo hwy/magellan av mir (08/06/15 11:03:58),1,traffic accident n cabrillo hwy/magellan av mir (08/06/15 11:03:58),traffic accident n cabrillo hwy/magellan av mir (08/06/15 11:03:58),"['traffic', 'accident', 'n', 'cabrillo', 'hwy', 'magellan', 'av', 'mir', '08', '06', '15', '11', '03', '58']","['traffic_accident', 'accident_n', 'n_cabrillo', 'cabrillo_hwy', 'hwy_magellan', 'magellan_av', 'av_mir', 'mir_08', '08_06', '06_15', '15_11', '11_03', '03_58']"
113,accident,North Carolina,i-77 mile marker 31 to 40 south mooresville  iredell vehicle accident congestion at 8/6 1:18 pm,1,i-77 mile marker 31 to 40 south mooresville  iredell vehicle accident congestion at 8/6 1:18 pm,i-77 mile marker 31 to 40 south mooresville  iredell vehicle accident congestion at 8/6 1:18 pm,"['77', 'mile', 'marker', '31', '40', 'south', 'mooresville', 'iredell', 'vehicle', 'accident', 'congestion', '8', '6', '1', '18', 'pm']","['77_mile', 'mile_marker', 'marker_31', '31_40', '40_south', 'south_mooresville', 'mooresville_iredell', 'iredell_vehicle', 'vehicle_accident', 'accident_congestion', 'congestion_8', '8_6', '6_1', '1_18', '18_pm']"
114,accident,"Njoro, Kenya",the pastor was not in the scene of the accident......who was the owner of the range rover ?,1,the pastor was not in the scene of the accident......who was the owner of the range rover ?,the pastor was not in the scene of the accident......who was the owner of the range rover ?,"['pastor', 'scene', 'accident', 'owner', 'range', 'rover']","['pastor_scene', 'scene_accident', 'accident_owner', 'owner_range', 'range_rover']"
117,accident,,mom: 'we didn't get home as fast as we wished' me: 'why is that?'mom: 'there was an accident and some truck spilt mayonnaise all over ??????,0,mom: 'we didn't get home as fast as we wished' me: 'why is that?'mom: 'there was an accident and some truck spilt mayonnaise all over ??????,mom: 'we didn't get home as fast as we wished' me: 'why is that?'mom: 'there was an accident and some truck spilt mayonnaise all over ??????,"['mom', 'get', 'home', 'fast', 'wished', 'mom', 'accident', 'truck', 'spilt', 'mayonnaise']","['mom_get', 'get_home', 'home_fast', 'fast_wished', 'wished_mom', 'mom_accident', 'accident_truck', 'truck_spilt', 'spilt_mayonnaise']"
118,accident,Your Sister's Bedroom,i was in a horrible car accident this past sunday. i'm finally able to get around. thank you god??,1,i was in a horrible car accident this past sunday. i'm finally able to get around. thank you god??,i was in a horrible car accident this past sunday. i'm finally able to get around. thank you god??,"['horrible', 'car', 'accident', 'past', 'sunday', 'finally', 'able', 'get', 'around', 'thank', 'god']","['horrible_car', 'car_accident', 'accident_past', 'past_sunday', 'sunday_finally', 'finally_able', 'able_get', 'get_around', 'around_thank', 'thank_god']"
119,accident,,can wait to see how pissed donnie is when i tell him i was in another accident??,0,can wait to see how pissed donnie is when i tell him i was in another accident??,can wait to see how pissed donnie is when i tell him i was in another accident??,"['wait', 'see', 'pissed', 'donnie', 'tell', 'another', 'accident']","['wait_see', 'see_pissed', 'pissed_donnie', 'donnie_tell', 'tell_another', 'another_accident']"
120,accident,"Arlington, TX",truckcrash overturns on fortworth interstate   click here if you've been in a crash&gt; ,1,truckcrash overturns on fortworth interstate   click here if you've been in a crash&gt; ,truckcrash overturns on fortworth interstate   click here if you've been in a crash&gt; ,"['truckcrash', 'overturns', 'fortworth', 'interstate', 'click', 'crash', 'gt']","['truckcrash_overturns', 'overturns_fortworth', 'fortworth_interstate', 'interstate_click', 'click_crash', 'crash_gt']"
121,accident,"South Bloomfield, OH",accident in ashville on us 23 sb before sr 752 traffic  ,1,accident in ashville on us 23 sb before sr 752 traffic  ,accident in ashville on us 23 sb before sr 752 traffic  ,"['accident', 'ashville', 'us', '23', 'sb', 'sr', '752', 'traffic']","['accident_ashville', 'ashville_us', 'us_23', '23_sb', 'sb_sr', 'sr_752', '752_traffic']"
126,accident,,carolina accident: motorcyclist dies in i-540 crash with car that crossed median: a motorcycle rider traveling...  ,1,carolina accident: motorcyclist dies in i-540 crash with car that crossed median: a motorcycle rider traveling...  ,carolina accident: motorcyclist dies in i-540 crash with car that crossed median: a motorcycle rider traveling...  ,"['carolina', 'accident', 'motorcyclist', 'dies', '540', 'crash', 'car', 'crossed', 'median', 'motorcycle', 'rider', 'traveling']","['carolina_accident', 'accident_motorcyclist', 'motorcyclist_dies', 'dies_540', '540_crash', 'crash_car', 'car_crossed', 'crossed_median', 'median_motorcycle', 'motorcycle_rider', 'rider_traveling']"
128,accident,"New Hanover County, NC",fyi cad:fyi: ;accident property damage;nhs;999 piner rd/horndale dr,1,fyi cad:fyi: ;accident property damage;nhs;999 piner rd/horndale dr,fyi cad:fyi: ;accident property damage;nhs;999 piner rd/horndale dr,"['fyi', 'cad', 'fyi', 'accident', 'property', 'damage', 'nhs', '999', 'piner', 'rd', 'horndale', 'dr']","['fyi_cad', 'cad_fyi', 'fyi_accident', 'accident_property', 'property_damage', 'damage_nhs', 'nhs_999', '999_piner', 'piner_rd', 'rd_horndale', 'horndale_dr']"
129,accident,Maldives,rt naayf: first accident in years. turning onto chandanee magu from near mma. taxi rammed into me while i was halfway turned. everyone confû_,1,rt naayf: first accident in years. turning onto chandanee magu from near mma. taxi rammed into me while i was halfway turned. everyone confû_,rt naayf: first accident in years. turning onto chandanee magu from near mma. taxi rammed into me while i was halfway turned. everyone confû_,"['rt', 'naayf', 'first', 'accident', 'years', 'turning', 'onto', 'chandanee', 'magu', 'near', 'mma', 'taxi', 'rammed', 'halfway', 'turned', 'everyone', 'conf', 'û_']","['rt_naayf', 'naayf_first', 'first_accident', 'accident_years', 'years_turning', 'turning_onto', 'onto_chandanee', 'chandanee_magu', 'magu_near', 'near_mma', 'mma_taxi', 'taxi_rammed', 'rammed_halfway', 'halfway_turned', 'turned_everyone', 'everyone_conf', 'conf_û_']"
130,accident,"Manchester, NH",accident left lane blocked in manchester on rt 293 nb before eddy rd stop and go traffic back to nh-3a delay of 4 mins traffic,1,accident left lane blocked in manchester on rt 293 nb before eddy rd stop and go traffic back to nh-3a delay of 4 mins traff,accident left lane blocked in manchester on rt 293 nb before eddy rd stop and go traffic back to nh-3a delay of 4 mins traff,"['accident', 'left', 'lane', 'blocked', 'manchester', 'rt', '293', 'nb', 'eddy', 'rd', 'stop', 'go', 'traffic', 'back', 'nh', '3a', 'delay', '4', 'mins', 'traff']","['accident_left', 'left_lane', 'lane_blocked', 'blocked_manchester', 'manchester_rt', 'rt_293', '293_nb', 'nb_eddy', 'eddy_rd', 'rd_stop', 'stop_go', 'go_traffic', 'traffic_back', 'back_nh', 'nh_3a', '3a_delay', 'delay_4', '4_mins', 'mins_traff']"
131,accident,"Wilmington, NC",;accident property damage; piner rd/horndale dr,1,;accident property damage; piner rd/horndale dr,;accident property damage; piner rd/horndale dr,"['accident', 'property', 'damage', 'piner', 'rd', 'horndale', 'dr']","['accident_property', 'property_damage', 'damage_piner', 'piner_rd', 'rd_horndale', 'horndale_dr']"
132,accident,,???? it was an accident  ,0,???? it was an accident  ,???? it was an accident  ,['accident'],[]
133,accident,"New Hanover County, NC",fyi cad:fyi: ;accident property damage;wpd;1600 s 17th st,1,fyi cad:fyi: ;accident property damage;wpd;1600 s 17th st,fyi cad:fyi: ;accident property damage;wpd;1600 s 17th st,"['fyi', 'cad', 'fyi', 'accident', 'property', 'damage', 'wpd', '1600', '17th', 'st']","['fyi_cad', 'cad_fyi', 'fyi_accident', 'accident_property', 'property_damage', 'damage_wpd', 'wpd_1600', '1600_17th', '17th_st']"
134,accident,,8/6/2015:09 pm: traffic accident no injury at 2781 willis foreman rd  ,1,8/6/2015:09 pm: traffic accident no injury at 2781 willis foreman rd  ,8/6/2015:09 pm: traffic accident no injury at 2781 willis foreman rd  ,"['8', '6', '2015', '09', 'pm', 'traffic', 'accident', 'injury', '2781', 'willis', 'foreman', 'rd']","['8_6', '6_2015', '2015_09', '09_pm', 'pm_traffic', 'traffic_accident', 'accident_injury', 'injury_2781', '2781_willis', 'willis_foreman', 'foreman_rd']"
135,accident,global,aashiqui actress anu aggarwal on her near-fatal accident  ,1,aashiqui actress anu aggarwal on her near-fatal accident  ,aashiqui actress anu aggarwal on her near-fatal accident  ,"['aashiqui', 'actress', 'anu', 'aggarwal', 'near', 'fatal', 'accident']","['aashiqui_actress', 'actress_anu', 'anu_aggarwal', 'aggarwal_near', 'near_fatal', 'fatal_accident']"
136,accident,Alberta | Sask. | Montana,suffield alberta accident  ,1,suffield alberta accident  ,suffield alberta accident  ,"['suffield', 'alberta', 'accident']","['suffield_alberta', 'alberta_accident']"
137,accident,Charlotte,9 mile backup on i-77 south...accident blocking the right 2 lanes at exit 31 langtree rd...consider nc 115 or nc 150 to nc 16 as alternate,1,9 mile backup on i-77 south...accident blocking the right 2 lanes at exit 31 langtree rd...consider nc 115 or nc 150 to nc 16 as altern,9 mile backup on i-77 south...accident blocking the right 2 lanes at exit 31 langtree rd...consider nc 115 or nc 150 to nc 16 as altern,"['9', 'mile', 'backup', '77', 'south', 'accident', 'blocking', 'right', '2', 'lanes', 'exit', '31', 'langtree', 'rd', 'consider', 'nc', '115', 'nc', '150', 'nc', '16', 'altern']","['9_mile', 'mile_backup', 'backup_77', '77_south', 'south_accident', 'accident_blocking', 'blocking_right', 'right_2', '2_lanes', 'lanes_exit', 'exit_31', '31_langtree', 'langtree_rd', 'rd_consider', 'consider_nc', 'nc_115', '115_nc', 'nc_150', '150_nc', 'nc_16', '16_altern']"
138,accident,"Baton Rouge, LA",has an accident changed your life? we will help you determine options that can financially support life care plans and on-going treatment.,0,has an accident changed your life? we will help you determine options that can financially support life care plans and on-going treatment.,has an accident changed your life? we will help you determine options that can financially support life care plans and on-going treatment.,"['accident', 'changed', 'life', 'help', 'determine', 'options', 'financially', 'support', 'life', 'care', 'plans', 'going', 'treatment']","['accident_changed', 'changed_life', 'life_help', 'help_determine', 'determine_options', 'options_financially', 'financially_support', 'support_life', 'life_care', 'care_plans', 'plans_going', 'going_treatment']"
139,accident,"Hagerstown, MD",breaking: there was a deadly motorcycle car accident that happened to hagerstown today. i'll have more details at 5 . whag,1,breaking: there was a deadly motorcycle car accident that happened to hagerstown today. i'll have more details at 5 . whag,breaking: there was a deadly motorcycle car accident that happened to hagerstown today. i'll have more details at 5 . whag,"['breaking', 'deadly', 'motorcycle', 'car', 'accident', 'happened', 'hagerstown', 'today', 'details', '5', 'whag']","['breaking_deadly', 'deadly_motorcycle', 'motorcycle_car', 'car_accident', 'accident_happened', 'happened_hagerstown', 'hagerstown_today', 'today_details', 'details_5', '5_whag']"
141,accident,"Gloucestershire , UK", were you marinading it or was it an accident?,0, were you marinading it or was it an accident?, were you marinading it or was it an accident?,"['marinading', 'accident']",['marinading_accident']
143,accident,,only had a car for not even a week and got in a fucking car accident .. mfs can't fucking drive .,1,only had a car for not even a week and got in a fucking car accident .. mfs can't fucking drive .,only had a car for not even a week and got in a fucking car accident .. mfs can't fucking drive .,"['car', 'even', 'week', 'got', 'fucking', 'car', 'accident', 'mfs', 'fucking', 'drive']","['car_even', 'even_week', 'week_got', 'got_fucking', 'fucking_car', 'car_accident', 'accident_mfs', 'mfs_fucking', 'fucking_drive']"
144,accident,UK,. bahrain police had previously died in a road accident they were not killed by explosion  ,1,. bahrain police had previously died in a road accident they were not killed by explosion  ,. bahrain police had previously died in a road accident they were not killed by explosion  ,"['bahrain', 'police', 'previously', 'died', 'road', 'accident', 'killed', 'explosion']","['bahrain_police', 'police_previously', 'previously_died', 'died_road', 'road_accident', 'accident_killed', 'killed_explosion']"
145,accident,"Nairobi, Kenya",i still have not heard church leaders of kenya coming forward to comment on the accident issue and disciplinary measuresarrestpastornganga,0,i still have not heard church leaders of kenya coming forward to comment on the accident issue and disciplinary measuresarrestpastornganga,i still have not heard church leaders of kenya coming forward to comment on the accident issue and disciplinary measuresarrestpastornganga,"['still', 'heard', 'church', 'leaders', 'kenya', 'coming', 'forward', 'comment', 'accident', 'issue', 'disciplinary', 'measuresarrestpastornganga']","['still_heard', 'heard_church', 'church_leaders', 'leaders_kenya', 'kenya_coming', 'coming_forward', 'forward_comment', 'comment_accident', 'accident_issue', 'issue_disciplinary', 'disciplinary_measuresarrestpastornganga']"
146,aftershock,Instagram - @heyimginog , scuf ps live and the game... cya,0, scuf ps live and the game... cya, scuf ps live and the game... cya,"['scuf', 'ps', 'live', 'game', 'cya']","['scuf_ps', 'ps_live', 'live_game', 'game_cya']"
149,aftershock,304,'the man who can drive himself further once the effort gets painful is the man who will win.' roger bannister,0,'the man who can drive himself further once the effort gets painful is the man who will win.' roger bannist,'the man who can drive himself further once the effort gets painful is the man who will win.' roger bannist,"['man', 'drive', 'effort', 'gets', 'painful', 'man', 'win', 'roger', 'bannist']","['man_drive', 'drive_effort', 'effort_gets', 'gets_painful', 'painful_man', 'man_win', 'win_roger', 'roger_bannist']"
151,aftershock,Switzerland,320 [ir] icemoon [aftershock] |   |  | dubstep trapmusic dnb edm dance icesû_  ,0,320 [ir] icemoon [aftershock] |   |  | dubstep trapmusic dnb edm dance icesû_  ,320 [ir] icemoon [aftershock] |   |  | dubstep trapmusic dnb edm dance icesû_  ,"['320', 'ir', 'icemoon', 'aftershock', 'dubstep', 'trapmusic', 'dnb', 'edm', 'dance', 'ices', 'û_']","['320_ir', 'ir_icemoon', 'icemoon_aftershock', 'aftershock_dubstep', 'dubstep_trapmusic', 'trapmusic_dnb', 'dnb_edm', 'edm_dance', 'dance_ices', 'ices_û_']"
153,aftershock,304,'there is no victory at bargain basement prices.' dwight david eisenhower,0,'there is no victory at bargain basement prices.' dwight david eisenhow,'there is no victory at bargain basement prices.' dwight david eisenhow,"['victory', 'bargain', 'basement', 'prices', 'dwight', 'david', 'eisenhow']","['victory_bargain', 'bargain_basement', 'basement_prices', 'prices_dwight', 'dwight_david', 'david_eisenhow']"
156,aftershock,US,320 [ir] icemoon [aftershock] |   |  | dubstep trapmusic dnb edm dance icesû_  ,0,320 [ir] icemoon [aftershock] |   |  | dubstep trapmusic dnb edm dance icesû_  ,320 [ir] icemoon [aftershock] |   |  | dubstep trapmusic dnb edm dance icesû_  ,"['320', 'ir', 'icemoon', 'aftershock', 'dubstep', 'trapmusic', 'dnb', 'edm', 'dance', 'ices', 'û_']","['320_ir', 'ir_icemoon', 'icemoon_aftershock', 'aftershock_dubstep', 'dubstep_trapmusic', 'trapmusic_dnb', 'dnb_edm', 'edm_dance', 'dance_ices', 'ices_û_']"
157,aftershock,304,'nobody remembers who came in second.' charles schulz,0,'nobody remembers who came in second.' charles schulz,'nobody remembers who came in second.' charles schulz,"['nobody', 'remembers', 'came', 'second', 'charles', 'schulz']","['nobody_remembers', 'remembers_came', 'came_second', 'second_charles', 'charles_schulz']"
158,aftershock,Instagram - @heyimginog , im speaking from someone that is using a scuf on xb1 most of them people will end up getting on for ps also.,0, im speaking from someone that is using a scuf on xb1 most of them people will end up getting on for ps also., im speaking from someone that is using a scuf on xb1 most of them people will end up getting on for ps also.,"['im', 'speaking', 'someone', 'using', 'scuf', 'xb1', 'people', 'end', 'getting', 'ps', 'also']","['im_speaking', 'speaking_someone', 'someone_using', 'using_scuf', 'scuf_xb1', 'xb1_people', 'people_end', 'end_getting', 'getting_ps', 'ps_also']"
159,aftershock,304,'the harder the conflict the more glorious the triumph.' thomas paine,0,'the harder the conflict the more glorious the triumph.' thomas pain,'the harder the conflict the more glorious the triumph.' thomas pain,"['harder', 'conflict', 'glorious', 'triumph', 'thomas', 'pain']","['harder_conflict', 'conflict_glorious', 'glorious_triumph', 'triumph_thomas', 'thomas_pain']"
160,aftershock,,growingupspoiled going clay pigeon shooting and crying because of the 'aftershock',0,growingupspoiled going clay pigeon shooting and crying because of the 'aftershock',growingupspoiled going clay pigeon shooting and crying because of the 'aftershock',"['growingupspoiled', 'going', 'clay', 'pigeon', 'shooting', 'crying', 'aftershock']","['growingupspoiled_going', 'going_clay', 'clay_pigeon', 'pigeon_shooting', 'shooting_crying', 'crying_aftershock']"
161,aftershock,Somewhere Only We Know ?,so i guess no one actually wants any free aftershock tc.....,0,so i guess no one actually wants any free aftershock tc.....,so i guess no one actually wants any free aftershock tc.....,"['guess', 'one', 'actually', 'wants', 'free', 'aftershock', 'tc']","['guess_one', 'one_actually', 'actually_wants', 'wants_free', 'free_aftershock', 'aftershock_tc']"
162,aftershock,,aftershock was the most terrifying best roller coaster i've ever been on. *disclaimer* i've been on very few.,0,aftershock was the most terrifying best roller coaster i've ever been on. *disclaimer* i've been on very few.,aftershock was the most terrifying best roller coaster i've ever been on. *disclaimer* i've been on very few.,"['aftershock', 'terrifying', 'best', 'roller', 'coaster', 'ever', 'disclaimer']","['aftershock_terrifying', 'terrifying_best', 'best_roller', 'roller_coaster', 'coaster_ever', 'ever_disclaimer']"
163,aftershock,Belgium,aftershock  ,0,aftershock  ,aftershock  ,['aftershock'],[]
164,aftershock,Switzerland,320 [ir] icemoon [aftershock] |   |  | dubstep trapmusic dnb edm dance icesû_  ,0,320 [ir] icemoon [aftershock] |   |  | dubstep trapmusic dnb edm dance icesû_  ,320 [ir] icemoon [aftershock] |   |  | dubstep trapmusic dnb edm dance icesû_  ,"['320', 'ir', 'icemoon', 'aftershock', 'dubstep', 'trapmusic', 'dnb', 'edm', 'dance', 'ices', 'û_']","['320_ir', 'ir_icemoon', 'icemoon_aftershock', 'aftershock_dubstep', 'dubstep_trapmusic', 'trapmusic_dnb', 'dnb_edm', 'edm_dance', 'dance_ices', 'ices_û_']"
165,aftershock,US,320 [ir] icemoon [aftershock] |   |  | dubstep trapmusic dnb edm dance icesû_  ,0,320 [ir] icemoon [aftershock] |   |  | dubstep trapmusic dnb edm dance icesû_  ,320 [ir] icemoon [aftershock] |   |  | dubstep trapmusic dnb edm dance icesû_  ,"['320', 'ir', 'icemoon', 'aftershock', 'dubstep', 'trapmusic', 'dnb', 'edm', 'dance', 'ices', 'û_']","['320_ir', 'ir_icemoon', 'icemoon_aftershock', 'aftershock_dubstep', 'dubstep_trapmusic', 'trapmusic_dnb', 'dnb_edm', 'edm_dance', 'dance_ices', 'ices_û_']"
168,aftershock,,320 [ir] icemoon [aftershock] |   |  | dubstep trapmusic dnb edm dance icesû_  ,0,320 [ir] icemoon [aftershock] |   |  | dubstep trapmusic dnb edm dance icesû_  ,320 [ir] icemoon [aftershock] |   |  | dubstep trapmusic dnb edm dance icesû_  ,"['320', 'ir', 'icemoon', 'aftershock', 'dubstep', 'trapmusic', 'dnb', 'edm', 'dance', 'ices', 'û_']","['320_ir', 'ir_icemoon', 'icemoon_aftershock', 'aftershock_dubstep', 'dubstep_trapmusic', 'trapmusic_dnb', 'dnb_edm', 'edm_dance', 'dance_ices', 'ices_û_']"
170,aftershock,dope show, i'm seeing them and issues at aftershock ??,0, i'm seeing them and issues at aftershock ??, i'm seeing them and issues at aftershock ??,"['seeing', 'issues', 'aftershock']","['seeing_issues', 'issues_aftershock']"
171,aftershock,Switzerland,320 [ir] icemoon [aftershock] |   |  | dubstep trapmusic dnb edm dance icesû_  ,0,320 [ir] icemoon [aftershock] |   |  | dubstep trapmusic dnb edm dance icesû_  ,320 [ir] icemoon [aftershock] |   |  | dubstep trapmusic dnb edm dance icesû_  ,"['320', 'ir', 'icemoon', 'aftershock', 'dubstep', 'trapmusic', 'dnb', 'edm', 'dance', 'ices', 'û_']","['320_ir', 'ir_icemoon', 'icemoon_aftershock', 'aftershock_dubstep', 'dubstep_trapmusic', 'trapmusic_dnb', 'dnb_edm', 'edm_dance', 'dance_ices', 'ices_û_']"
''')]
